### ISSUE TITLE
Windows version OneDrive login error

### ISSUE THREAD

**Issue by WizardofOzDK** [Styrit/shopadoo.styrit.com#3]
![17343593205627709144695640248358](https://github.com/user-attachments/assets/dca0f28e-2fa7-4f9b-b915-03102cae17f5)

I love your app and am and use it every week. I  believe recent changes to the windows login api have disabled the windows version from synching to OneDrive. I like to search for recipes and make my shopping list on my deshtop, and use the phone when in the sopeemarket. I hope you have time and it's an easy fix... Karl

**Comment by gp-slick-coder** [comment]
hi Karl, thanks for the report.

If you have version 2.4.2 the issue should be fixed.
https://shopadoo.styrit.com/#/About
